#Numpy 28/12/66

In [1]:
import numpy as np

In [2]:
a = [1,2,3,4,5]

In [3]:
np1 = np.array(a)

In [4]:
a

[1, 2, 3, 4, 5]

In [5]:
type(np1)

numpy.ndarray

In [7]:
b = np.zeros( 5 , dtype = int)

In [8]:
b

array([0, 0, 0, 0, 0])

In [9]:
b = np.zeros( [3,5] , dtype = int)
b

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [10]:
c = np.ones(6)
c

array([1., 1., 1., 1., 1., 1.])

In [12]:
c = np.ones([3,4])
c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
d = np.full([3,5],6)
d

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [16]:
e = np.arange(10)
print(e)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
e = np.arange(1,10,2)
print(e)

[1 3 5 7 9]


In [19]:
e = np.arange(10,0,-2)
print(e)

[10  8  6  4  2]


In [24]:
f = np.linspace(1,10,10)
f

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [35]:
b = np.eye(4,5,-1,dtype=int)
b

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [41]:
h = np.empty([4,5])
print(h)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [91]:
a = np.random.randint(100)
print(a)

43


In [93]:
from numpy import random as rd

In [95]:
rd.randint(20)

7

In [96]:
rd.rand()

0.573156474355466

In [97]:
rd.rand(5)

array([0.5779784 , 0.73665911, 0.60413847, 0.83470071, 0.7898281 ])

In [98]:
rd.rand(3,4)

array([[0.1934378 , 0.84647278, 0.93785356, 0.54196343],
       [0.39774722, 0.81369128, 0.09205826, 0.3544715 ],
       [0.39817652, 0.21407031, 0.16901868, 0.92619321]])

In [102]:
rd.randint(size = [3,5],low = 50,high = 100)

array([[98, 97, 99, 91, 63],
       [92, 54, 97, 61, 50],
       [81, 74, 60, 84, 74]])

In [105]:
rd.randint(20,50)

38

In [106]:
lst = ['Gold','Silver','Carbon']

In [122]:
rd.choice(lst)

'Carbon'

In [124]:
rd.choice(lst,size=10)

array(['Gold', 'Silver', 'Gold', 'Carbon', 'Silver', 'Silver', 'Gold',
       'Silver', 'Silver', 'Silver'], dtype='<U6')

In [129]:
c = rd.choice(lst,size=20,p=[0.1,0.3,0.6])
print(c)

['Silver' 'Silver' 'Carbon' 'Carbon' 'Silver' 'Carbon' 'Carbon' 'Carbon'
 'Gold' 'Carbon' 'Silver' 'Carbon' 'Carbon' 'Silver' 'Silver' 'Carbon'
 'Carbon' 'Silver' 'Silver' 'Carbon']


In [132]:
a = [1,2,3,4,5]

In [133]:
a

[1, 2, 3, 4, 5]

In [134]:
rd.shuffle(a)

In [135]:
a

[4, 3, 1, 5, 2]

In [136]:
rd.permutation(a)

array([5, 1, 3, 2, 4])

In [137]:
a

[4, 3, 1, 5, 2]

In [138]:
a = rd.randint(0,100,20)

In [139]:
a

array([44, 58, 41, 24, 85,  6, 82, 22, 82, 14, 82, 30, 87, 61, 55, 58,  7,
       46, 83, 74])

In [140]:
a.reshape(4,5)

array([[44, 58, 41, 24, 85],
       [ 6, 82, 22, 82, 14],
       [82, 30, 87, 61, 55],
       [58,  7, 46, 83, 74]])

In [144]:
a.reshape(-1)

array([44, 58, 41, 24, 85,  6, 82, 22, 82, 14, 82, 30, 87, 61, 55, 58,  7,
       46, 83, 74])

In [145]:
lst1 = [1,2,3]
lst2 = [4,5,6]

In [146]:
lst1+lst2

[1, 2, 3, 4, 5, 6]

In [147]:
nlst1 = np.array(lst1)
nlst2 = np.array(lst2)

In [148]:
nlst1**nlst2

array([  1,  32, 729])

In [149]:
nlst3 = np.array([10])

In [150]:
nlst2+nlst3

array([14, 15, 16])

In [152]:
a = np.arange(50).reshape(5,10)
b = np.arange(5).reshape(5,1)
print(a,b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]] [[0]
 [1]
 [2]
 [3]
 [4]]


In [154]:
c = a*b
print(c)

[[  0   0   0   0   0   0   0   0   0   0]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 40  42  44  46  48  50  52  54  56  58]
 [ 90  93  96  99 102 105 108 111 114 117]
 [160 164 168 172 176 180 184 188 192 196]]


In [155]:
a = rd.randint(0,100,size=[4,5])
a

array([[58, 21, 94, 98, 73],
       [34, 67, 36, 80, 53],
       [30, 80, 20, 37,  1],
       [ 0, 94, 30, 82, 81]])

In [156]:
a[2][4]

1

In [157]:
a[2,4]

1

In [158]:
a[-1,2]

30

In [159]:
a

array([[58, 21, 94, 98, 73],
       [34, 67, 36, 80, 53],
       [30, 80, 20, 37,  1],
       [ 0, 94, 30, 82, 81]])

In [166]:
a[0: :2 , :]

array([[58, 21, 94, 98, 73],
       [30, 80, 20, 37,  1]])

In [167]:
a[ [0,1,3] , : ]

array([[58, 21, 94, 98, 73],
       [34, 67, 36, 80, 53],
       [ 0, 94, 30, 82, 81]])